<?php
declare(strict_types=1);
// Minimal password-reset page that accepts a token link (?token=...) and lets the user set a new password.
// Adjust DB credentials if needed.

error_reporting(E_ALL);
ini_set('display_errors', '0');

function h(string $s): string { return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }

$DB_HOST = '127.0.0.1';
$DB_USER = 'root';
$DB_PASS = '';
$DB_NAME = 'Inventory_system_db';

$mysqli = @new mysqli($DB_HOST, $DB_USER, $DB_PASS, $DB_NAME);
if ($mysqli->connect_errno) {
    http_response_code(500);
    echo 'Database connection error.';
    exit;
}
$mysqli->set_charset('utf8mb4');

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$tokenRaw = trim((string)($_GET['token'] ?? $_POST['token'] ?? ''));

// Basic token sanity check (64 hex chars as generated by send_reset_email)
$validTokenFormat = preg_match('/^[0-9a-f]{64}$/i', $tokenRaw);

$errors = [];
$success = '';

if ($method === 'POST') {
    $pw = (string)($_POST['password'] ?? '');
    $pw2 = (string)($_POST['password_confirm'] ?? '');

    if (!$validTokenFormat) {
        $errors[] = 'Invalid or missing token.';
    }
    if (strlen($pw) < 8) {
        $errors[] = 'Password must be at least 8 characters.';
    }
    if ($pw !== $pw2) {
        $errors[] = 'Passwords do not match.';
    }

    if (empty($errors)) {
        $tokenHash = hash('sha256', $tokenRaw);

        // Find matching user with non-expired token
        $stmt = $mysqli->prepare('SELECT user_id FROM users WHERE password_reset_token = ? AND password_reset_expires >= NOW() AND status = "active" LIMIT 1');
        if ($stmt) {
            $stmt->bind_param('s', $tokenHash);
            $stmt->execute();
            $res = $stmt->get_result();
            $user = $res->fetch_assoc();
            $stmt->close();

            if ($user && isset($user['user_id'])) {
                $newHash = password_hash($pw, PASSWORD_DEFAULT);
                $upd = $mysqli->prepare('UPDATE users SET password = ?, password_reset_token = NULL, password_reset_expires = NULL, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?');
                if ($upd) {
                    $upd->bind_param('si', $newHash, $user['user_id']);
                    if ($upd->execute()) {
                        $success = 'Your password has been updated. You may now <a href="login.php">log in</a>.';
                    } else {
                        $errors[] = 'Unable to update password. Try again later.';
                    }
                    $upd->close();
                } else {
                    $errors[] = 'Server error.';
                }
            } else {
                $errors[] = 'Invalid or expired token.';
            }
        } else {
            $errors[] = 'Server error.';
        }
    }
}

// If GET and token missing or invalid then show simple message
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Reset Password - INVENTORY Management System</title>
    <link rel="stylesheet" href="../css/main.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
</head>
<body class="min-h-screen bg-gradient-to-br from-primary-50 to-secondary-100 flex items-center justify-center p-4">
    <!-- Background Pattern -->
    <div class="absolute inset-0 opacity-10">
        <svg class="w-full h-full" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
            <defs>
                <pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse">
                    <path d="M 10 0 L 0 0 0 10" fill="none" stroke="currentColor" stroke-width="0.5"/>
                </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#grid)" class="text-primary-300"/>
        </svg>
    </div>

    <!-- Main Container -->
    <div class="relative w-full max-w-md">
        <!-- Security Badge -->
        <div class="flex justify-center mb-6">
            <div class="flex items-center space-x-2 bg-white/80 backdrop-blur-sm px-4 py-2 rounded-full shadow-sm border border-border-light">
                <i class="fas fa-key text-success-600 text-sm"></i>
                <span class="text-xs font-medium text-text-secondary">Password Reset</span>
            </div>
        </div>

        <!-- Password Reset Card -->
        <div class="bg-white/95 backdrop-blur-sm rounded-2xl shadow-xl border border-white/20 p-8 animation-slide-up">
            <!-- Logo and Header -->
            <div class="text-center mb-8">
                <div class="inline-flex items-center justify-center w-16 h-16 bg-primary-100 rounded-2xl mb-4">
                    <svg class="w-8 h-8 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z"/>
                    </svg>
                </div>
                <h1 class="text-2xl font-semibold text-text-primary mb-2">Reset Password</h1>
                <p class="text-text-secondary">Enter your new password below</p>
            </div>

            <?php if ($success): ?>
                <div class="mb-6 p-4 bg-success-50 border border-success-200 rounded-xl">
                    <div class="flex items-center">
                        <i class="fas fa-check-circle text-success-600 mr-2"></i>
                        <span class="text-sm text-success-700"><?php echo $success; ?></span>
                    </div>
                </div>
            <?php else: ?>
                <?php if (!empty($errors)): ?>
                    <div class="mb-6 p-4 bg-error-50 border border-error-200 rounded-xl">
                        <ul class="text-sm text-error-700">
                            <?php foreach ($errors as $e) { echo '<li class="mb-1">' . h($e) . '</li>'; } ?>
                        </ul>
                    </div>
                <?php endif; ?>

                <?php if (!$validTokenFormat): ?>
                    <div class="text-center p-8 bg-gray-50 rounded-xl border-2 border-dashed border-gray-300">
                        <i class="fas fa-exclamation-triangle text-warning-500 text-3xl mb-4"></i>
                        <h3 class="font-semibold text-text-primary mb-2">Invalid Reset Link</h3>
                        <p class="text-sm text-text-secondary">The reset link is invalid or has expired. Please request a new password reset.</p>
                    </div>
                <?php else: ?>
                    <form method="post" class="space-y-6" novalidate>
                        <input type="hidden" name="token" value="<?php echo h($tokenRaw); ?>">
                        
                        <!-- New Password Field -->
                        <div class="space-y-2">
                            <label for="password" class="block text-sm font-medium text-text-primary">
                                New Password
                            </label>
                            <div class="relative">
                                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                    <i class="fas fa-lock text-text-tertiary text-sm"></i>
                                </div>
                                <input type="password" id="password" name="password" required minlength="8" autocomplete="new-password" 
                                       class="w-full pl-10 pr-4 py-3 border border-border-light rounded-xl focus:ring-2 focus:ring-primary-200 focus:border-primary-500 transition-all duration-200 bg-white/50" 
                                       placeholder="Enter new password">
                            </div>
                        </div>

                        <!-- Confirm Password Field -->
                        <div class="space-y-2">
                            <label for="password_confirm" class="block text-sm font-medium text-text-primary">
                                Confirm Password
                            </label>
                            <div class="relative">
                                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                    <i class="fas fa-lock text-text-tertiary text-sm"></i>
                                </div>
                                <input type="password" id="password_confirm" name="password_confirm" required minlength="8" autocomplete="new-password"
                                       class="w-full pl-10 pr-4 py-3 border border-border-light rounded-xl focus:ring-2 focus:ring-primary-200 focus:border-primary-500 transition-all duration-200 bg-white/50"
                                       placeholder="Confirm new password">
                            </div>
                        </div>
                        
                        <!-- Reset Button -->
                        <button type="submit" class="w-full bg-primary hover:bg-primary-700 text-white font-medium py-3 px-4 rounded-xl transition-all duration-200 transform hover:scale-[1.02] focus:ring-2 focus:ring-primary-200 focus:ring-offset-2 shadow-lg">
                            <span class="flex items-center justify-center">
                                <i class="fas fa-key mr-2"></i>
                                Reset Password
                            </span>
                        </button>
                    </form>
                <?php endif; ?>
            <?php endif; ?>
        </div>

        <!-- Footer -->
        <div class="text-center mt-8">
            <p class="text-xs text-text-tertiary">
                © 2025 INVENTORY Management System. All Rights Reserved.
            </p>
        </div>
    </div>
</body>
</html>
<?php
$mysqli->close();
exit;
?>